name: Candidate Form
description: Fill out this form to request joining our organization.
title: "[Join Request] - {your name}"
labels: [candidate]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in joining our organization! Please provide the following information:

  - type: input
    id: name
    attributes:
      label: "Your Full Name"
      placeholder: "Enter your full name"
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: "Your Email Address"
      placeholder: "Enter your email address"
    validations:
      required: true
      format: email

  - type: textarea
    id: reason
    attributes:
      label: "Why do you want to join our organization?"
      placeholder: "Provide your reasons here"
    validations:
      required: true

  - type: input
    id: github_username
    attributes:
      label: "Your GitHub Username"
      placeholder: "Enter your GitHub username"
    validations:
      required: true

  - type: input
    id: project_link
    attributes:
      label: "Link to Your Project"
      placeholder: "Enter a link to your project"
    validations:
      required: true
      format: url

  - type: checkbox
    id: agree
    attributes:
      label: "I agree to abide by the organization's code of conduct."
    validations:
      required: true
